--- #YAML:1.0
name:               Glib-Ex-ConnectProperties
version:            18
abstract:           Link properties between objects.
author:
    - Kevin Ryde <user42@zip.com.au>
license:            gpl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Glib:                 0
    Glib::Ex::SignalIds:  5
    Glib::Object::Subclass:  0
    Module::Load:         0
    perl:                 5.008
resources:
    homepage:  http://user42.tuxfamily.org/glib-ex-connectproperties/index.html
    license:   http://www.gnu.org/licenses/gpl.html
no_index:
    directory:
        - t
        - inc
        - devel
        - xt
        - devel
        - examples
        - maybe
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
optional_features:
    maximum_examples:
        description:  Be able to run all the example programs.
        requires:
            Gtk2:  0
    maximum_tests:
        description:  Have "make test" do as much as possible.
        requires:
            Gtk2:          0
            Module::Util:  0
            Test::Weaken:  2.002
recommends:
    DateTime:            0
    DateTime::TimeZone:  0
